### ISSUE TITLE
V1.13.4 Compilation error

### ISSUE THREAD

**Issue by lxm520** [umijs/babel-plugin-import#610]
`ERROR in ./src/app/index.js
Module build failed (from ./node_modules/happypack/loader.js):
Error: Cannot find module '/Users/chencheng/code/github.com/umijs/babel-plugin-import/node_modules/.pnpm/babel-preset-umi@1.8.4/node_modules/@babel/runtime/helpers/interopRequireDefault'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/liuxiaomeng/Desktop/weimob/extension/saas-fe-sirius-ggvert/node_modules/babel-plugin-import/lib/index.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
 @ multi ./src/app/index.js index[0]`

The code compilation reports an error, which should be a missubmission.

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/babel-plugin-import/issues/613。
